version: "3"
services:
  app:
    image: efcore-sample-app
    build: .
    volumes:
      - .:/work
    working_dir: /work
    links:
      - db:db.local
  db:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
